os: osx
osx_image: xcode10.2

matrix:
  include:
    - language: node_js
      os: linux
      node_js:
        - "11"

      install:
        - cd website
        - yarn
        - cd ..

      script:
        - cd website
        - yarn build
        - cd ..

      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          fqdn: fbflipper.com
          local-dir: website/build/flipper
          keep-history: true
          on:
            branch: master
    - language: node_js
      os: linux
      node_js:
        - "11"

      install:
        - cd desktop
        - yarn

      script:
        - cd desktop
        - yarn lint
        - yarn test
        - yarn build --linux --version=$TRAVIS_BUILD_NUMBER

    - language: objective-c
      cache:
        cocoapods: true
        directories:
          - $HOME/Library/Caches/CocoaPods/Pods/Release/


      before_install:
        - gem install cocoapods
        - pod --version
        - rm -f iOS/Sample/Podfile.lock
        - rm -f iOS/Sample/build.log
        - rm -f iOS/SampleSwift/Podfile.lock
        - pod repo update --silent

      install:
        - cd iOS/Sample
        - rm -f Podfile.lock
        - travis_wait 30 pod install --silent
        - cd ../../

      script:
        - cd iOS/Sample
        - IPHONESIMULATOR=$(xcodebuild -showsdks | grep -o "iphonesimulator[0-9]\\+\\.[0-9]\\+$")
        - travis_wait 30 xcodebuild build -workspace Sample.xcworkspace -scheme Sample -sdk $IPHONESIMULATOR -quiet > ./build.log
        - tail -100 ./build.log

    - language: objective-c
      cache:
        cocoapods: true
        directories:
          - $HOME/Library/Caches/CocoaPods/Pods/Release/

      before_install:
        - gem install cocoapods
        - pod --version
        - rm -f iOS/SampleSwift/Podfile.lock
        - rm -f iOS/SampleSwift/build.log
        - pod repo update --silent

      install:
        - cd iOS/SampleSwift
        - rm -f Podfile.lock
        - travis_wait 30 pod install --silent
        - cd ../../
      script:
        - cd iOS/SampleSwift
        - IPHONESIMULATOR=$(xcodebuild -showsdks | grep -o "iphonesimulator[0-9]\\+\\.[0-9]\\+$")
        - travis_wait xcodebuild build -workspace SampleSwift.xcworkspace -scheme SampleSwift -sdk $IPHONESIMULATOR -quiet > ./build.log
        - tail -100 ./build.log
